POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "slavoljub1234@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:5000/users/sign-up
Content-Type: application/json

{
    "email": "slavoljsubssssd1ss@gmail.com",
    "password": "12345678"
}
###

GET http://localhost:5000/users/me/access-token
Content-Type: application/json
_id:6494e674ef010e2d53c0b083
x-refresh-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5ZjU2MDFkNzU3MGYzMDkzY2JiYzYiLCJpYXQiOjE2ODc4MTE0MjQsImV4cCI6MTY4NzgxMjQyNH0.GEUasB6zbVi-Vr4qEPYMM_PDsIDvJwVfKZt8nbm1OWA

###

GET http://localhost:5000/lists
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk5ZjU2MDFkNzU3MGYzMDkzY2JiYzYiLCJpYXQiOjE2ODc4MTE0MjQsImV4cCI6MTY4NzgxMjQyNH0.GEUasB6zbVi-Vr4qEPYMM_PDsIDvJwVfKZt8nbm1OWA
