POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "slavoljub123@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:5000/users/sign-up
Content-Type: application/json

{
    "email": "slavoljusdab1d223ffs3@gmail.com",
    "password": "12345678"
}
###

GET http://localhost:5000/users/me/access-token
Content-Type: application/json
_id:6494e674ef010e2d53c0b083
x-refresh-token:9846e529ebc2500e821d98d657ddaad4cb60be2606bcdb5c566185e19e1aca4aa46ca3ee9de371e87eb2d62aa76d6ad4389869c4ef7eae97b945eaf9c5e93369